[theme]
base = "light"
primaryColor = "#6B5BFF"
backgroundColor = "#F5F6FB"
secondaryBackgroundColor = "#ECEEF8"
textColor = "#151833"
font = "sans serif"

[server]
maxUploadSize = 300

[client]
toolbarMode = "minimal"
