[theme]
base = "light"
primaryColor = "#2446E0"
backgroundColor = "#FAFBFD"
secondaryBackgroundColor = "#EEF2F8"
textColor = "#10204A"
font = "sans serif"

[server]
maxUploadSize = 300

[client]
toolbarMode = "minimal"
